name: mercan_app
description: Mercan App.
publish_to: "none"
version: 1.0.4+5

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.4
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
