name: togu_yemekhane
description: TOGU Yemekhane.
publish_to: "none"
version: 1.0.6+7

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.12.1
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.4
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
